name: eopf-binder
channels:
  - conda-forge
dependencies:
  # Essential packages
  - python=3.9
  - jupyter
  - jupyterlab
  - gdal>=3.8
  - libgdal>=3.8
  - numpy
  - xarray
  - zarr<3
  - matplotlib
  - ipywidgets
  
  # Build tools for driver build
  - cmake
  - make
  - compilers
  - pkg-config
  - git
  - cxx-compiler
  - c-compiler
  
  # Additional GDAL dependencies
  - proj
  - geos
  
  # Pip packages
  - pip
  - pip:
    - rasterio
    - geopandas
