name: eopf-binder
channels:
  - conda-forge
dependencies:
  # Essential packages only
  - python=3.9
  - jupyter
  - jupyterlab
  - gdal=3.6.*
  - numpy
  - xarray
  - zarr<3
  - matplotlib
  - ipywidgets
  
  # Build tools for optional driver build
  - cmake
  - make
  - compilers
  
  # Pip packages
  - pip
  - pip:
    - rasterio
