name: eopf-zarr-driver
channels:
  - conda-forge
  - defaults
dependencies:
  # Core scientific computing
  - numpy
  - scipy  
  - pandas
  - matplotlib
  
  # Geospatial and Earth Observation
  - gdal>=3.10
  - xarray
  - zarr<3
  - dask
  - geopandas
  - rasterio
  - fiona
  - shapely
  - pyproj
  - cartopy
  
  # Data formats
  - netcdf4
  - h5py
  
  # Jupyter ecosystem
  - jupyter
  - jupyterlab
  - jupyterhub
  - ipywidgets
  - ipykernel
  - notebook
  - nbclassic
  
  # Development and testing
  - pytest
  - pytest-cov
  
  # Additional utilities
  - pip
  - git
