name: Build EOPF container images

on: 
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'eopf-dask/**'
      - 'eopf-zarr-driver/**'
      - '.github/workflows/build.yaml'


jobs:
  build-dask-image:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # Make sure buildx is used
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to EOPF Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://harbor.user.eopf.eodc.eu/
          username: ${{ secrets.HARBOR_ROBOT_USER }}
          password: ${{ secrets.HARBOR_ROBOT_PWD }}
      
      # Build and push image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: harbor.user.eopf.eodc.eu/jupyterdask/eopf-dask:latest
          file: eopf-dask/eopf-dask.dockerfile

  build-zarr-driver-image:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Make sure buildx is used
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to EOPF Container Registry
      - name: Log in to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: https://harbor.user.eopf.eodc.eu/
          username: ${{ secrets.HARBOR_ROBOT_USER }}
          password: ${{ secrets.HARBOR_ROBOT_PWD }}
      
      # Build and push image (single platform for speed)
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./eopf-zarr-driver
          platforms: linux/amd64
          push: true
          tags: harbor.user.eopf.eodc.eu/jupyterdask/eopf-zarr-driver:latest
          file: ./eopf-zarr-driver/Dockerfile
